### ISSUE TITLE
Class def not found

### ISSUE THREAD

**Issue by yatzy** [kgcorner/chess-archiver#1]
Hi,

Thanks for writing this. I'm facing an 
`Error: Unable to initialize main class com.kgcorner.Chess
Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient
`
error while trying to download my games

**Comment by kgcorner** [comment]
Looks like a genuine issue. Let me update you after correcting this.

**Comment by kgcorner** [comment]
I am sorry for the huge delay in resolving this issue. I have updated the downloaded executable and added a basic stat as well.

Please download from [here](https://kgcorner.com/chess-archiver.zip) 

It's a zip file. To use it. extract the zip file and there you'll find the required jar file and depended libs. Execute the command from location where jar file and lib directory is located

**Comment by yatzy** [comment]
Thank you, working great!
